"""The PDF policy certificate. Returns bytes; the caller decides where to store them."""
import io

import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Image, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from insurance_core.catalogue import product_name

WATERMARK = "PROTOTYPE - NOT VALID"


def ngn(amount: float) -> str:
    return f"NGN {amount:,.0f}"          # built-in PDF fonts have no ₦ glyph; it would print as a black box


def pdf_safe(text) -> str:
    return str(text).replace("₦", "NGN ")


def _qr_image(url: str) -> Image:
    buffer = io.BytesIO()
    qrcode.make(url).save(buffer, format="PNG")
    buffer.seek(0)
    return Image(buffer, width=38 * mm, height=38 * mm)


def _watermark(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Bold", 44)
    canvas.setFillColor(colors.Color(0.8, 0, 0, alpha=0.08))
    canvas.translate(A4[0] / 2, A4[1] / 2)
    canvas.rotate(40)
    canvas.drawCentredString(0, 0, WATERMARK)
    canvas.restoreState()


def build_certificate(record: dict, rec: dict, policyholder_name: str, verify_url: str,
                      versions_note: str = "", insurer_name: str = "Demo Insurance Ltd") -> bytes:
    styles = getSampleStyleSheet()
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=8, textColor=colors.grey)
    warn = ParagraphStyle("warn", parent=styles["Normal"], fontSize=9, textColor=colors.HexColor("#B00020"))
    grid = TableStyle([("FONTSIZE", (0, 0), (-1, -1), 9), ("TEXTCOLOR", (0, 0), (0, -1), colors.grey),
                       ("BOTTOMPADDING", (0, 0), (-1, -1), 4), ("VALIGN", (0, 0), (-1, -1), "TOP")])

    story = [
        Paragraph("Policy Certificate", styles["Title"]),
        Paragraph(f"{insurer_name} | generated by the ML Insurance Recommendation System", small),
        Paragraph("PROTOTYPE: this document is not a valid insurance contract.", warn),
        Spacer(1, 8 * mm),
    ]
    details = Table([
        ["Policy number", record["policy_number"]],
        ["Product", f"{product_name(record['product_code'])} ({record['product_code']})"],
        ["Policyholder", policyholder_name],
        ["Customer ID", record["customer_id"]],
        ["Period of cover", f"{record['start_date']} to {record['end_date']}"],
        ["Status", record["status"].upper()],
    ], colWidths=[40 * mm, 80 * mm], style=grid)
    story.append(Table([[details, _qr_image(verify_url)]], colWidths=[124 * mm, 46 * mm],
                       style=TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP")])))
    story.append(Paragraph("Scan the QR code to confirm this policy is genuine.", small))
    story.append(Spacer(1, 6 * mm))

    story.append(Paragraph("Premium and payment", styles["Heading3"]))
    story.append(Table([
        ["Annual premium", ngn(record["premium_ngn"])],
        ["Payment plan", f"{record['payment_plan']} ({ngn(record['payment_ngn'])} per payment)"],
        ["Total payable", ngn(record["total_ngn"])],
    ], colWidths=[40 * mm, 120 * mm], style=grid))

    story.append(Paragraph("How your premium was calculated", styles["Heading3"]))
    rows = [["Step", "Running total"]] + [[pdf_safe(step), ngn(amount)] for step, amount in rec["breakdown"]]
    story.append(Table(rows, colWidths=[120 * mm, 40 * mm], style=TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9), ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("LINEBELOW", (0, 0), (-1, 0), 0.5, colors.grey), ("ALIGN", (1, 0), (1, -1), "RIGHT")])))

    if rec["notes"]:
        story.append(Paragraph("Important notes", styles["Heading3"]))
        for note in rec["notes"]:
            story.append(Paragraph(f"&bull; {pdf_safe(note)}", styles["Normal"]))

    story.append(Spacer(1, 8 * mm))
    footer = f"Verification code: {record['signature']} | Issued {record['created_at']}"
    if versions_note:
        footer += f" | {versions_note}"
    story.append(Paragraph(footer, small))

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, topMargin=18 * mm, bottomMargin=18 * mm,
                            leftMargin=18 * mm, rightMargin=18 * mm,
                            title=f"Policy {record['policy_number']}", author=insurer_name)
    doc.build(story, onFirstPage=_watermark)
    return buffer.getvalue()